// ═══════════════════════════════════════════════════════
// Auto-generated by @php-websocket-rpc/codegen.
// Do not edit this file directly.
// ═══════════════════════════════════════════════════════

import type { ProxyOptions } from '@php-websocket-rpc/client';

// ───── MathService ─────
export interface MathServiceProxy {
    add(a: number, b: number): Promise<number>;
    sub(a: number, b: number): Promise<number>;
    mul(a: number, b: number): Promise<number>;
    log(message: string): void;
}

// ───── NumberStreamService ─────
export interface NumberStreamServiceProxy {
    count(limit: number): AsyncIterable<number>;
}

// ───── EventService ─────
export interface EventServiceProxy {
    onEvent(callback: (value: string) => void): void;
}

// ───── ChatService ─────
export interface ChatServiceProxy {
    onMessage(callback: (value: unknown) => void): void;
    send(message: string): void;
}

export const MathServiceConfig = {
    service: 'MathService',
    call: ['add', 'sub', 'mul'],
    notify: ['log'],
} satisfies ProxyOptions;

export const NumberStreamServiceConfig = {
    service: 'NumberStreamService',
    stream: ['count'],
} satisfies ProxyOptions;

export const EventServiceConfig = {
    service: 'EventService',
    subscribe: ['onEvent'],
    channel: 'events',
} satisfies ProxyOptions;

export const ChatServiceConfig = {
    service: 'ChatService',
    subscribe: ['onMessage'],
    publish: ['send'],
    channel: 'chat',
} satisfies ProxyOptions;
